# Generated by Django 4.0.3 on 2022-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BW', 'Bottom Wear'), ('TW', 'Top Wear'), ('M', 'Mobile'), ('L', 'Laptop'), ('B', 'Book')], max_length=2),
        ),
    ]
